version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=dancedivision
      - POSTGRES_PASSWORD=dance123
    ports:
      - "5432:5432"